spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true

  web:
    resources:
      static-locations:
        - classpath:/static/

server:
  port: ${PORT:8080}

api:
  security:
    token:
      secret: ${JWT_SECRET}